<a href="https://colab.research.google.com/github/abbyleppert/Data-Science/blob/main/Abby_Leppert_homework_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

In [79]:
import numpy as np


### Loops

In [ ]:
for i in range(100):
    print(i)

In [2]:
# prints  a range of numbers from 1-100

In [ ]:
for i in range(5,8):
    print(i)

In [4]:
#prints specific range of numbers(5-8)

In [5]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


In [6]:
# prints a range of 3 numbers with a title of "test number"

### Functions

In [7]:
def square(x):
    return x**2

In [8]:
#squares x by using **2

In [9]:
square(5)

25

In [10]:
#squares 5 which is 25

In [11]:
square(square(2))

16

In [12]:
#squares 2 twice which will end up being 4x4

In [13]:
square(square(square(2)))


256

In [14]:
# repeatedly adds squares on creating the number generated 

In [15]:
square(123456)

15241383936

In [16]:
# squares 123456

In [17]:
square(square(5))

625

In [19]:
# squares 5 twice

In [20]:
def add_two(x):
    return x+2

In [21]:
#code add_two will add two to whatever number is in the parenthesis 

In [22]:
add_two(5)

7

In [23]:
# adds two to 5 which is 7

In [24]:
square(add_two(5))

49

In [25]:
#squares 7 because it was add_two to a 5 before getting squared

### Logical Branching

In [26]:
choice = "apple"

In [27]:
#creates a choice

In [28]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [29]:
#prints you choose apples when you choose apples

In [30]:
choice = "orange"

In [31]:
#new choice is orange 

In [32]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [33]:
#since the choice is apples, it will print you did not choose apples

In [34]:
choice = "apple"

In [35]:
#back tof irst choice

In [36]:
if choice == "apple":

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


In [37]:
# Since the choice is apples, it will print everything that is under the if choice including the recepit number 

### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ")

In [41]:
# Leaves a spot for an answer 

In [42]:
choice

'apple'

In [43]:
#will display choice 

In [44]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


In [45]:
# will show you what you have chosen 

#### Coins

In [ ]:
np.random.random()

In [ ]:
np.random.random() > 0.5

In [ ]:
def flip_coin():
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [ ]:
flip_coin()

### Graphics Output

In [47]:
from IPython.core.display import display, HTML

In [46]:
# imports from ipython 

In [48]:
display(HTML('<h1>Hello, world!</h1>'))

In [49]:
#display code, can tell it what to say

In [50]:
def coin():
  return np.random.randint(2)

In [51]:
# random coin 

In [81]:
coin()

0

In [85]:
# had to add import numpy as np at the top for it tot work 

In [54]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [55]:
# displays an image with the url

In [60]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [56]:
#gives a url for both heads and tails 

In [57]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [61]:
show_img(heads)

In [64]:
#shows the image from url

In [62]:
show_img(tails)

In [63]:
#shows the iage from url

In [65]:
def flip_coin():

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [66]:
#will show head or tails image when you say flip_coin 

In [82]:
flip_coin()

In [83]:
for i in range(5):
    flip_coin()

In [73]:
#randomly flips coin 5 times

In [84]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

In [ ]:
# shows random coin flip

### Cards

In [76]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [77]:
# putting in a shuffle code so that when you tell it to shuffle it will shuffle the deck of cards

In [80]:
a = np.arange(52)

In [86]:
# adds arrange of numbers 

In [87]:
shuffle(a)

array([40,  8,  3, 31, 41, 20, 34, 25, 38, 45,  0, 42, 29, 43, 10, 16,  6,
       17, 21, 50,  7, 49,  5, 44, 36, 14, 46, 13, 27, 18, 30, 47, 28, 26,
       23, 19, 22, 48, 51, 15, 33, 11, 35, 32, 39, 24,  4, 37,  2, 12,  1,
        9])

In [ ]:
# gives a shuffle of cards 1-52

In [88]:
np.random.permutation(52)

array([14, 26, 20, 49, 44, 45,  2, 16, 17, 12, 47, 35, 29,  0, 43, 21,  5,
       13, 37,  4, 24, 22,  8, 34, 39, 28, 27, 11, 42, 41, 10, 51, 32, 19,
       36, 46,  9, 18, 23, 38, 48,  1, 33,  6, 25, 31,  3,  7, 50, 30, 40,
       15])

In [89]:
# gives another arrange 

### Speed Test

In [90]:
%%timeit
shuffle(a)

173 µs ± 1.43 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [91]:
#meausres the exucation time of the cell

In [92]:
%%timeit
np.random.permutation(52)

3.5 µs ± 239 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [93]:
# measures with a random permutation (52)

In [94]:
import numpy as np

In [95]:
#needed to import random permutations

In [96]:
np.random.permutation(52)

array([16,  6, 51,  0,  8, 38, 50, 17, 10, 34, 40, 11,  4, 43, 27, 12, 21,
       28,  5, 25, 49, 14, 45, 48, 35,  2, 24,  3, 30, 37, 33, 31, 13, 47,
       15, 29,  7, 42, 18, 19, 46, 36, 26, 44, 32, 23, 41, 20,  1, 39, 22,
        9])

In [97]:
# random array of numbers 1-52

In [98]:
cards = np.random.permutation(52)

In [99]:
# the word card will now give a random permutation of a number 1-52

In [100]:
cards

array([27,  1, 12, 45, 49, 14, 22, 34, 37, 17,  7, 15, 33, 26,  9, 47, 36,
       21, 30, 19, 43,  3,  4,  8, 40, 24, 44, 41, 23, 28, 10, 42,  0, 11,
       13,  5, 16, 51, 29, 32, 20, 50, 38, 48,  6, 25, 35,  2, 46, 39, 31,
       18])

In [101]:
# random cards

In [102]:
cards[0]

27

In [103]:
#each card pulled with the number will be different in parenthesis

In [104]:
cards[1]

1

In [106]:
#same decription as a above 

In [107]:
cards[2]

12

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [108]:
np.arange(52).reshape(4,13)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [109]:
#another arrange

In [110]:
np.arange(52).reshape(4,13)%13

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [113]:
#arrange with the 13% at the end creates the same pattern ??

In [112]:
np.arange(52).reshape(4,13)//13

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [114]:
# reshapes so that each layer of numbers is the same 

In [115]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [116]:
# inserts name for each possibel card

In [117]:
def card_name(card_number):
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [118]:
# will say card name and suit with card_name code

In [119]:
card_name(0)

'Ace of Clubs'

In [120]:
#tells you the card from 0

In [121]:
card_name(51)

'King of Diamonds'

In [122]:
#tells me what card was 51

In [123]:
cards = np.random.permutation(52)

In [124]:
# random card genorate

In [125]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [126]:
# Tells you what card are on the top, second and last in the deck 

In [127]:
top_of_deck, second_card_in_deck, last_card_in_deck

('King of Spades', 'Ten of Diamonds', 'Ace of Clubs')

In [128]:
# random cards on top, second or last card of the deck.

In [129]:
for i in range(5):
    print(card_name(cards[i]))

King of Spades
Ten of Diamonds
Seven of Diamonds
Five of Spades
Eight of Spades


In [131]:
# random 5 card names pulled

In [132]:
for i in range(15):
    print(card_name(cards[i]))

King of Spades
Ten of Diamonds
Seven of Diamonds
Five of Spades
Eight of Spades
Five of Clubs
Three of Diamonds
Four of Diamonds
Nine of Clubs
King of Hearts
Ace of Spades
Ace of Diamonds
Six of Clubs
Ten of Hearts
Eight of Diamonds


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [133]:
# 15 random card names pulled 

In [134]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"
card_url_tail = ".png"

In [135]:
# uploads images for each card

In [136]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [137]:
#numbers and suits can now be said by a single letter or number

In [138]:
i = np.random.randint(4)
j = np.random.randint(13)

In [139]:
#random randint code

In [140]:
i,j

(2, 4)

In [ ]:
# generates random cards

In [141]:
suit[i]

's'

In [143]:
#generates random suit

In [142]:
card[j]

'5'

In [144]:
#generates random card number 

In [145]:
from IPython.core.display import display, HTML

In [146]:
#display the website 

In [147]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [148]:
# show image from website with show_image

In [149]:
img = card_url_head + suit[i] + card[j] + card_url_tail

In [150]:
# img will show what suit and card it is with an image 

In [151]:
show_img(img)

In [152]:
# shows an image of a random card from the deck 

In [153]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [154]:
card_image(3)

'k4'

In [155]:
# im not sure what these two mean ^^

In [156]:
img = card_url_head + card_image(3) + card_url_tail

In [157]:
# same code as last time but smaller?

In [164]:
show_img(img)

In [159]:
# shows card from deck

In [ ]:
# shows 52 cards from the deck in order 

In [165]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)